apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: {{ .Values.web.image }}
          volumeMounts:
            - name: test-results
              mountPath: /app/test_results
            - name: docker-socket
              mountPath: /var/run/docker.sock  # Монтирование сокета Docker
      volumes:
        - name: test-results
          emptyDir: {}
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock  # Путь на хосте
            type: Socket
